//This header is generated by CMake, do not edit it. (Changes will be lost)
// Instead edit SopaSpades.h.in, and run CMake again.

#define SopaSpades_VERSION_MAJOR 0
#define SopaSpades_VERSION_MINOR 1
#define SopaSpades_VERSION_REVISION 3

#define OS_STRINGIFY2(x)		#x
#define OS_STRINGIFY(x)			OS_STRINGIFY2(x)

#define OPENSPADES_EXTRATITLE	""
// #define SopaSpades_VER_STR		"SopaSpades " OS_STRINGIFY(SopaSpades_VERSION_MAJOR) "." OS_STRINGIFY(SopaSpades_VERSION_MINOR) "." OS_STRINGIFY(SopaSpades_VERSION_REVISION) OPENSPADES_EXTRATITLE
#define SopaSpades_VER_STR		"# SOPA SPADES 🔫🍜 #"
#define PACKAGE_STRING			SopaSpades_VER_STR

#define OPENSPADES_COMPILER_STR	"GNU 9.4.0"

#define SDL_VERSION_STR			""
#define ZLIB_VERSION_STR		"1.2.11"
#define CURL_VERSION_STR		"7.68.0"

/* #undef RESDIR_DEFINED */
#define RESDIR ""

#define CMAKE_INSTALL_PREFIX "/usr/local"
#define OPENSPADES_INSTALL_RESOURCES "share/games/sopaspades/Resources"
